// LOGIN PAGE
export const FACEBOOK_LOGIN_SUCCESS = 'FACEBOOK_LOGIN_SUCCESS';
export const FACEBOOK_LOGIN_FAIL = 'FACEBOOK_LOGIN_FAIL';
export const FACEBOOK_FETCH_DETAILS = 'FACEBOOK_FETCH_DETAILS';
export const EMAIL_LOGIN_CHANGED = 'EMAIL_LOGIN_CHANGED';
export const PASSWORD_LOGIN_CHANGED = 'PASSWORD_LOGIN_CHANGED';
export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const REQUEST_LOGIN_WITH_TOKEN = 'REQUEST_LOGIN_WITH_TOKEN';
export const REQUESTED_LOGIN_SUCCEEDED = 'REQUESTED_LOGIN_SUCCEEDED';
export const REQUESTED_LOGIN_ERROR = 'REQUESTED_LOGIN_ERROR';

//FORGOT PASSWORD MODULE
export const FORGOTPASSWORD_SUBMIT = 'FORGOTPASSWORD_SUBMIT';
export const FORGOTPASSWORD_SUBMIT_SUCCEEDED = 'FORGOTPASSWORD_SUBMIT_SUCCEEDED';
export const FORGOTPASSWORD_SUBMIT_ERROR = 'FORGOTPASSWORD_SUBMIT_ERROR';

//RESET PASSWORD MODULE
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_SUCCEEDED = 'RESET_PASSWORD_SUCCEEDED';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';

// REGISTER PAGE
export const REQUEST_USER_REG = 'REQUEST_USER_REG';
export const REG_USER_SUCCESS = 'REG_USER_SUCCESS';
export const REG_USER_FAIL = 'REG_USER_FAIL';
export const GENERATE_OTP_SUCCESS = 'GENERATE_OTP_SUCCESS';
export const GENERATE_OTP_FAIL = 'GENERATE_OTP_FAIL';
export const REQUEST_VERIFY_OTP = 'REQUEST_VERIFY_OTP';
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS';
export const VERIFY_OTP_FAIL = 'VERIFY_OTP_FAIL';
export const CHANGE_PHONE_NUMBER = 'CHANGE_PHONE_NUMBER';
export const CHANGE_PHONE_NUMBER_ERROR = 'CHANGE_PHONE_NUMBER_ERROR';

//PROFILE PAGE
export const GET_MY_PROFILE_INFO = 'GET_MY_PROFILE_INFO';
export const GET_PROFILE_INFO = 'GET_PROFILE_INFO';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const SET_LOCATION = 'SET_LOCATION';
export const REQUEST_REGISTER_MAVEN = 'REQUEST_REGISTER_MAVEN';
export const REGISTER_MAVEN = 'REGISTER_MAVEN';
export const REGISTER_MAVEN_ERROR = 'REGISTER_MAVEN_ERROR';
export const ACTIVATE_MAVEN = 'ACTIVATE_MAVEN';
export const ACTIVATE_MAVEN_ERROR = 'ACTIVATE_MAVEN_ERROR';
export const DEACTIVATE_MAVEN = 'DEACTIVATE_MAVEN';
export const DEACTIVATE_MAVEN_ERROR = 'DEACTIVATE_MAVEN_ERROR';
export const DELETE_MAVEN = 'DELETE_MAVEN';
export const DELETE_MAVEN_ERROR = 'DELETE_MAVEN_ERROR';
export const REQUEST_ADD_MAVEN_IMAGE = 'REQUEST_ADD_MAVEN_IMAGE';
export const ADD_MAVEN_IMAGE = 'ADD_MAVEN_IMAGE';
export const ADD_MAVEN_IMAGE_ERROR = 'ADD_MAVEN_IMAGE_ERROR';
export const REQUEST_DELETE_MAVEN_IMAGE = 'REQUEST_DELETE_MAVEN_IMAGE';
export const DELETE_MAVEN_IMAGE = 'DELETE_MAVEN_IMAGE';
export const DELETE_MAVEN_IMAGE_ERROR = 'DELETE_MAVEN_IMAGE_ERROR';
export const CHECK_ID = 'CHECK_ID';
export const CHECK_ID_ERROR = 'CHECK_ID_ERROR';
export const REQUEST_EDIT_MAVEN_DETAILS = 'REQUEST_EDIT_MAVEN_DETAILS';
export const EDIT_MAVEN_DETAILS = 'EDIT_MAVEN_DETAILS';
export const EDIT_MAVEN_DETAILS_ERROR = 'EDIT_MAVEN_DETAILS_ERROR';
export const EDIT_ABOUT = 'EDIT_ABOUT';
export const EDIT_ABOUT_ERROR = 'EDIT_ABOUT_ERROR';
export const SAVE_MAVEN = 'SAVE_MAVEN';
export const SAVE_MAVEN_ERROR = 'SAVE_MAVEN_ERROR';
export const REPORT_MAVEN = 'REPORT_MAVEN';
export const REPORT_MAVEN_ERROR = 'REPORT_MAVEN_ERROR';
export const REQUEST_UPDATE_PROFILE_IMAGE = 'REQUEST_UPDATE_PROFILE_IMAGE';
export const UPDATE_PROFILE_IMAGE = 'UPDATE_PROFILE_IMAGE';
export const UPDATE_PROFILE_IMAGE_ERROR = 'UPDATE_PROFILE_IMAGE_ERROR';
export const GIVE_APP_FEEDBACK = 'GIVE_APP_FEEDBACK';
export const GIVE_APP_FEEDBACK_ERROR = 'GIVE_APP_FEEDBACK_ERROR';

//EXPLORE
export const GET_NEARBY_LIST = 'GET_NEARBY_LIST';
export const GET_NEARBY_LIST_ERROR = 'GET_NEARBY_LIST_ERROR';
export const GET_CAT_LIST = 'GET_CAT_LIST';
export const GET_CAT_LIST_ERROR = 'GET_CAT_LIST_ERROR';
export const GET_MAVEN_DETAILS = 'GET_MAVEN_DETAILS';
export const GET_MAVEN_DETAILS_ERROR = 'GET_MAVEN_DETAILS_ERROR';

//ACTIVITY
export const GET_ACTIVITIES_MY_SKILLS = 'GET_ACTIVITIES_MY_SKILLS';
export const GET_ACTIVITIES_REQUESTED_SKILLS = 'GET_ACTIVITIES_REQUESTED_SKILLS';
export const GET_ACTIVITIES_ARCHIVED_SKILLS = 'GET_ACTIVITIES_ARCHIVED_SKILLS';
export const GET_ACTIVITIES_ERROR = 'GET_ACTIVITIES_ERROR';
export const INIT_CHAT = 'INIT_CHAT';
export const INIT_CHAT_ERROR = 'INIT_CHAT_ERROR';
export const CREATE_OFFER_REQUEST = 'CREATE_OFFER_REQUEST'
export const CREATE_OFFER = 'CREATE_OFFER';
export const CREATE_OFFER_ERROR = 'CREATE_OFFER_ERROR';
export const ACCEPT_OFFER_REQUEST = 'ACCEPT_OFFER_REQUEST'
export const ACCEPT_OFFER = 'ACCEPT_OFFER';
export const ACCEPT_OFFER_ERROR = 'ACCEPT_OFFER_ERROR';
export const REJECT_OFFER_REQUEST = 'REJECT_OFFER_REQUEST'
export const REJECT_OFFER = 'REJECT_OFFER';
export const REJECT_OFFER_ERROR = 'REJECT_OFFER_ERROR';
export const CANCEL_OFFER_REQUEST = 'CANCEL_OFFER_REQUEST'
export const CANCEL_OFFER = 'CANCEL_OFFER';
export const CANCEL_OFFER_ERROR = 'CANCEL_OFFER_ERROR';
export const EDIT_OFFER_REQUEST = 'EDIT_OFFER_REQUEST'
export const EDIT_OFFER = 'EDIT_OFFER';
export const EDIT_OFFER_ERROR = 'EDIT_OFFER_ERROR';
export const END_JOB_REQUEST = 'END_JOB_REQUEST'
export const END_JOB = 'END_JOB';
export const END_JOB_ERROR = 'END_JOB_ERROR';
export const ARCHIVE_ACTIVITY_REQUEST = 'ARCHIVE_ACTIVITY_REQUEST'
export const ARCHIVE_ACTIVITY = 'ARCHIVE_ACTIVITY';
export const ARCHIVE_ACTIVITY_ERROR = 'ARCHIVE_ACTIVITY_ERROR';
export const REVIEW_ACTIVITY_REQUEST = 'REVIEW_ACTIVITY_REQUEST';
export const REVIEW_ACTIVITY = 'REVIEW_ACTIVITY';
export const REVIEW_ACTIVITY_ERROR = 'REVIEW_ACTIVITY_ERROR';
export const GET_MAVEN_ACTIVITIES = 'GET_MAVEN_ACTIVITIES';
export const GET_MAVEN_ACTIVITIES_ERROR = 'GET_MAVEN_ACTIVITIES_ERROR';

//TOPIC
export const GET_TOPIC_COUNT = 'GET_TOPIC_COUNT';
export const GET_TOPIC_COUNT_ERROR = 'GET_TOPIC_COUNT_ERROR';
export const GET_TOPICS = 'GET_TOPICS';
export const GET_TOPICS_ERROR = 'GET_TOPICS_ERROR';
export const CREATE_TOPIC = 'CREATE_TOPIC';
export const CREATE_TOPIC_ERROR = 'CREATE_TOPIC_ERROR';
export const SET_LIKE = 'SET_LIKE';
export const SET_LIKE_ERROR = 'SET_LIKE_ERROR';
export const GET_COMMENTS = 'GET_COMMENTS';
export const GET_COMMENTS_ERROR = 'GET_COMMENTS_ERROR';
export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_COMMENT_ERROR = 'ADD_COMMENT_ERROR';

//NOTIFICATION
export const SAVE_PUSH_TOKEN = 'SAVE_PUSH_TOKEN';
export const SAVE_PUSH_TOKEN_ERROR = 'SAVE_PUSH_TOKEN_ERROR';
export const SEND_PUSH_NOTIFICATION = 'SEND_PUSH_NOTIFICATION';
export const SEND_PUSH_NOTIFICATION_ERROR = 'SEND_PUSH_NOTIFICATION_ERROR';