// LOGIN PAGE
export const FACEBOOK_LOGIN_SUCCESS = 'FACEBOOK_LOGIN_SUCCESS';
export const FACEBOOK_LOGIN_FAIL = 'FACEBOOK_LOGIN_FAIL';
export const FACEBOOK_FETCH_DETAILS = 'FACEBOOK_FETCH_DETAILS';
export const EMAIL_LOGIN_CHANGED = 'EMAIL_LOGIN_CHANGED';
export const PASSWORD_LOGIN_CHANGED = 'PASSWORD_LOGIN_CHANGED';
export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const REQUESTED_LOGIN_SUCCEEDED = 'REQUESTED_LOGIN_SUCCEEDED';
export const REQUESTED_LOGIN_ERROR = 'REQUESTED_LOGIN_ERROR';

//FORGOT PASSWORD MODULE
export const FORGOTPASSWORD_SUBMIT = 'FORGOTPASSWORD_SUBMIT';
export const FORGOTPASSWORD_SUBMIT_SUCCEEDED = 'FORGOTPASSWORD_SUBMIT_SUCCEEDED';
export const FORGOTPASSWORD_SUBMIT_ERROR = 'FORGOTPASSWORD_SUBMIT_ERROR';

//RESET PASSWORD MODULE
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_SUCCEEDED = 'RESET_PASSWORD_SUCCEEDED';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';

// REGISTER PAGE
export const REQUEST_USER_REG = 'REQUEST_USER_REG';
export const REG_USER_SUCCESS = 'REG_USER_SUCCESS';
export const REG_USER_FAIL = 'REG_USER_FAIL';
export const GENERATE_OTP_SUCCESS = 'GENERATE_OTP_SUCCESS';
export const GENERATE_OTP_FAIL = 'GENERATE_OTP_FAIL';
export const REQUEST_VERIFY_OTP = 'REQUEST_VERIFY_OTP';
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS';
export const VERIFY_OTP_FAIL = 'VERIFY_OTP_FAIL';

//PROFILE PAGE
export const GET_MY_PROFILE_INFO = 'GET_MY_PROFILE_INFO';
export const GET_PROFILE_INFO = 'GET_PROFILE_INFO';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const SET_LOCATION = 'SET_LOCATION';
export const REQUEST_REGISTER_MAVEN = 'REQUEST_REGISTER_MAVEN';
export const REGISTER_MAVEN = 'REGISTER_MAVEN';
export const REGISTER_MAVEN_ERROR = 'REGISTER_MAVEN_ERROR';
export const ACTIVATE_MAVEN = 'ACTIVATE_MAVEN';
export const ACTIVATE_MAVEN_ERROR = 'ACTIVATE_MAVEN_ERROR';
export const DEACTIVATE_MAVEN = 'DEACTIVATE_MAVEN';
export const DEACTIVATE_MAVEN_ERROR = 'DEACTIVATE_MAVEN_ERROR';
export const DELETE_MAVEN = 'DELETE_MAVEN';
export const DELETE_MAVEN_ERROR = 'DELETE_MAVEN_ERROR';
export const REQUEST_ADD_MAVEN_IMAGE = 'REQUEST_ADD_MAVEN_IMAGE';
export const ADD_MAVEN_IMAGE = 'ADD_MAVEN_IMAGE';
export const ADD_MAVEN_IMAGE_ERROR = 'ADD_MAVEN_IMAGE_ERROR';
export const REQUEST_DELETE_MAVEN_IMAGE = 'REQUEST_DELETE_MAVEN_IMAGE';
export const DELETE_MAVEN_IMAGE = 'DELETE_MAVEN_IMAGE';
export const DELETE_MAVEN_IMAGE_ERROR = 'DELETE_MAVEN_IMAGE_ERROR';
export const CHECK_ID = 'CHECK_ID';
export const CHECK_ID_ERROR = 'CHECK_ID_ERROR';
export const REQUEST_EDIT_MAVEN_DETAILS = 'REQUEST_EDIT_MAVEN_DETAILS';
export const EDIT_MAVEN_DETAILS = 'EDIT_MAVEN_DETAILS';
export const EDIT_MAVEN_DETAILS_ERROR = 'EDIT_MAVEN_DETAILS_ERROR';

//EXPLORE
export const GET_NEARBY_LIST = 'GET_NEARBY_LIST';
export const GET_NEARBY_LIST_ERROR = 'GET_NEARBY_LIST_ERROR';
export const GET_CAT_LIST = 'GET_CAT_LIST';
export const GET_CAT_LIST_ERROR = 'GET_CAT_LIST_ERROR';
export const GET_MAVEN_DETAILS = 'GET_MAVEN_DETAILS';
export const GET_MAVEN_DETAILS_ERROR = 'GET_MAVEN_DETAILS_ERROR';
export const GET_TOPIC_COUNT = 'GET_TOPIC_COUNT';
export const GET_TOPIC_COUNT_ERROR = 'GET_TOPIC_COUNT_ERROR';

//ACTIVITY
export const CREATE_OFFER = 'CREATE_OFFER';
export const CREATE_OFFER_ERROR = 'CREATE_OFFER_ERROR';